branch-defaults:
  default:
    environment: lap-times-tracker-env
    group_suffix: null
  main:
    environment: lap-times-tracker-env
global:
  application_name: rc-laptimes-website
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js 20 running on 64bit Amazon Linux 2023
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
